Vagrant.configure(2) do |config|
  config.vm.box = "styleguide-ide"
  config.vm.hostname = "styleguide-ide"
  config.vm.synced_folder "../test-project/backbase", "/backbase"
  config.ssh.username = 'vagrant'
  config.vm.provision :shell, path: "bootstrap.sh", privileged: false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 3000, host: 3000
end